version: '3.7'

services:
  frontend:
    image: asf-web:v4.4
    build:
      context: .
    container_name: asf-web
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://asf-server:3333
    networks:
      - asf-network

networks:
  asf-network:
    external: true
